### ISSUE TITLE
Error trying to use DSC_Analysis module

### ISSUE THREAD

**Issue by kliron** [QIICR/DSC_Analysis#3]
I am on 3D slicer 4.11.20210226 r29738 / 7a593c8

I am trying perform a standard DSC analysis, have loaded my MultiVolume image and selected ROI and AIF masks. When I press "Apply" I get the following error 

```
DSCMRIAnalysis standard error:

/Applications/Slicer.app/Contents/Extensions-29738/DSCMRIAnalysis/lib/Slicer-4.11/cli-modules/DSCMRIAnalysis: exception caught !

itk::ExceptionObject (0x7fe571fb5530)
Location: "unknown" 
File: /Volumes/D/S/S-1-build/ITK/Modules/Core/Common/include/itkImageSource.hxx
Line: 273
Description: itk::ERROR: itk::ERROR: SignalIntensityToS0ImageFilter(0x7fe571fb4200): Subclass should override this method!!! If old behavior is desired invoke this->DynamicMultiThreadingOff(); before Update() is called. The best place is in class constructor.
```

I am guessing a deprecated call in the code that hasn't been fixed in the ITK 4 to 5 migration. After seeing [this](https://github.com/QIICR/DSC_Analysis/issues/1) closed issue I understand this module is no longer maintained. It would be kind of you to write that in the README stating that it is no longer working in the current version of 3D slicer and maybe point out which version was last compatible. It would save some time and maybe prompt some potential maintainer to step up. It is a pity that at present there are no open-source DSC analysis modules.

Thanks.

**Comment by kliron** [comment]
Just added a [pull request](https://github.com/QIICR/DSC_Analysis/pull/4) that fixes the issue. The module works with latest slicer build (4.13.0).

**Comment by fedorov** [comment]
Resolved by the aforementioned PR, as can be seen from the dashboard https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=dsc
